apiVersion: batch/v1
kind: Job
metadata:
  name: influx-backup-job
spec:
  template:
    spec:
      containers:
      - name: influx-backup
        image: mbelot/influx-backup:v0.1.0
      restartPolicy: Never
