apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: monitoring
---
# https://github.com/helm/helm/blob/master/docs/rbac.md#example-deploy-tiller-in-a-namespace-restricted-to-deploying-resources-only-in-that-namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: monitoring
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["endpoints"]
  verbs: ["get"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: monitoring
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io