apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: influxdbs.influxdata.com
spec:
  group: influxdata.com
  names:
    kind: Influxdb
    listKind: InfluxdbList
    plural: influxdbs
    singular: influxdb
  scope: Namespaced
  version: v1alpha1
