apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
  name: resize
parameters:
  type: gp2 
provisioner: kubernetes.io/aws-ebs 
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Gi
  storageClassName: resize
